# Generated by Django 4.1.1 on 2022-10-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_friend_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='roomName',
        ),
    ]
