# Generated by Django 4.1.1 on 2022-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_friend_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='roomName',
            field=models.CharField(default='error', max_length=100),
            preserve_default=False,
        ),
    ]
