# Generated by Django 4.1.1 on 2022-12-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_alter_message_datesent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
