# Generated by Django 4.1.1 on 2022-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_alter_message_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='isUnread',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
